spring:
  application:
    name: gateway
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: consumer-service
        uri: lb://protal
        predicates:
        - Path=/user/**
        filters:
        - StripPrefix=1

      - id: common-service
        uri: lb://common
        predicates:
        - Path=/common/**
        filters:
        - StripPrefix=1

      - id: fdfs-service
        uri: lb://fdfs
        predicates:
        - Path=/fdfs/**
        filters:
        - StripPrefix=1



server:
  port: 9995
  tomcat:
    uri-encoding: UTF-8

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/

logging:
  file:
    max-size: 20MB
  level:
    root: info
    org.springframework.web: info
    sample.mybatis.mapper: info
    org.springframework.cloud.gateway: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
  path: /data/gateway

test: 2344