spring:
  application:
    name: common
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

server:
  port: 9998
  tomcat:
    uri-encoding: UTF-8


eureka:
  instance:
    hostname: localhost
    data-center-info:
      appname: common
  client:
    enabled: true
    instanceInfoReplicationIntervalSeconds: 30
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/


logging:
  file:
    max-size: 20MB
  level:
    root: info
    org.springframework.web: info
    sample.mybatis.mapper: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
  path: /data/common


